### ISSUE TITLE
[BUG] CI tests failing against OpenSearch main and 2.x

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-net#268]
### What is the bug?
CI tests are failing for integration tests against OpenSearch 2.x and main after several attempts. https://github.com/opensearch-project/opensearch-net/pull/267

### How can one reproduce the bug?
See CI actions in https://github.com/opensearch-project/opensearch-net/pull/267

### What is the expected behavior?
Tests should pass.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by Xtansia** [comment]
Looks to be a variety of classpath issues in starting up the unreleased OpenSearch with plugins:

Need to investigate if this is an issue in our setup, upstream bugs, or managed to catch middle of breaking code-changes or stale/mismatched artifacts somewhere.

## 2.x 
https://github.com/opensearch-project/opensearch-net/actions/runs/5503973825/jobs/10029707791?pr=265#step:10:1404 
```
java.lang.NoClassDefFoundError: org/opensearch/core/common/io/stream/BaseStreamInput
	at org.opensearch.security.action.configupdate.ConfigUpdateAction.<init>(ConfigUpdateAction.java:37) 
	at org.opensearch.security.action.configupdate.ConfigUpdateAction.<clinit>(ConfigUpdateAction.java:33) 
	at org.opensearch.security.OpenSearchSecurityPlugin.getActions(OpenSearchSecurityPlugin.java:570) 
	at org.opensearch.action.ActionModule.lambda$setupActions$3(ActionModule.java:714)
```

## main
https://github.com/opensearch-project/opensearch-net/actions/runs/5503973825/jobs/10029707902?pr=265#step:10:1139
```
java.lang.NoSuchMethodError: 'void org.opensearch.index.codec.CodecService.<init>(org.opensearch.index.mapper.MapperService, org.apache.logging.log4j.Logger)'
	at org.opensearch.knn.index.codec.KNNCodecService.<init>(KNNCodecService.java:21) ~[?:?]
	at org.opensearch.index.engine.EngineConfigFactory.newCodecServiceOrDefault(EngineConfigFactory.java:201) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.shard.IndexShard.newEngineConfig(IndexShard.java:3695) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
```

**Comment by Yury-Fridlyand** [comment]
This probably caused by breaking changes in core (OpenSearch). Unless it is distributed over downstream projects (plugins), cluster can't start with them.
We had the same errors with different classes last releases while working on SQL plugin.
Possible solutions there:
1. Wait while plugin teams apply fixes
2. Ping them to apply fixes
3. Apply fix by yourself

Alternative ways are:
1. Use `latest stable` version instead of `latest`; somehow track updates
2. Skip plugins which are outdated in CI runtime and skip corresponding tests
