### ISSUE TITLE
[BUG] GitHubIssue4573.SerializePercentageScore test is flaky

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-net#443]
### What is the bug?
The `GitHubIssue4573.SerializePercentageScore` test is flaky and occasionally fails with a NullReferenceException. This needs investigating and fixing.
```
2023-11-13T10:32:06.2557024Z [xUnit.net 00:00:00.91]     Tests.Reproduce.GitHubIssue4573.SerializePercentageScore [FAIL]
2023-11-13T10:32:06.4981087Z   Failed Tests.Reproduce.GitHubIssue4573.SerializePercentageScore [234 ms]
2023-11-13T10:32:06.4982466Z   Error Message:
2023-11-13T10:32:06.4983991Z    Did not expect any exception, but found OpenSearch.Net.UnexpectedOpenSearchClientException: Object reference not set to an instance of an object.
2023-11-13T10:32:06.4986342Z  ---> System.NullReferenceException: Object reference not set to an instance of an object.
2023-11-13T10:32:06.4989148Z    at Tests.Reproduce.GitHubIssue5363.<>c.<DiagnosticListener_AuditTrailIsValid>b__1_0(IApiCallDetails data) in /home/runner/work/opensearch-net/opensearch-net/tests/Tests.Reproduce/GitHubIssue5363.cs:line 81
2023-11-13T10:32:06.4992820Z    at Tests.Reproduce.GitHubIssue5363.TestDiagnosticListener.<OnNext>b__9_1(KeyValuePair`2 v) in /home/runner/work/opensearch-net/opensearch-net/tests/Tests.Reproduce/GitHubIssue5363.cs:line 56
2023-11-13T10:32:06.4997556Z    at OpenSearch.Net.Diagnostics.TypedDiagnosticObserverBase`2.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Net/Diagnostics/TypedDiagnosticObserverBase.cs:line 93
2023-11-13T10:32:06.5000961Z    at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
2023-11-13T10:32:06.5003062Z    at System.Diagnostics.DiagnosticSource.StopActivity(Activity activity, Object args)
2023-11-13T10:32:06.5006337Z    at OpenSearch.Net.Diagnostics.Diagnostic`2.Dispose() in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Net/Diagnostics/Diagnostic.cs:line 76
2023-11-13T10:32:06.5010001Z    at OpenSearch.Net.RequestPipeline.Ping(Node node) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Net/Transport/Pipeline/RequestPipeline.cs:line 420
2023-11-13T10:32:06.5013384Z    at OpenSearch.Net.Transport`1.Ping(IRequestPipeline pipeline, Node node) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Net/Transport/Transport.cs:line 260
2023-11-13T10:32:06.5017246Z    at OpenSearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Net/Transport/Transport.cs:line 100
2023-11-13T10:32:06.5019636Z    --- End of inner exception stack trace ---
2023-11-13T10:32:06.5022217Z    at OpenSearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Net/Transport/Transport.cs:line 119
2023-11-13T10:32:06.5026649Z    at OpenSearch.Net.OpenSearchLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Net/OpenSearchLowLevelClient.cs:line 94
2023-11-13T10:32:06.5031189Z    at OpenSearch.Client.OpenSearchClient.DoRequest[TRequest,TResponse](TRequest p, IRequestParameters parameters, Action`1 forceConfiguration) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Client/OpenSearchClient.cs:line 151
2023-11-13T10:32:06.5035163Z    at OpenSearch.Client.OpenSearchClient.Search[TDocument](ISearchRequest request) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Client/OpenSearchClient.NoNamespace.cs:line 873
2023-11-13T10:32:06.5038652Z    at OpenSearch.Client.OpenSearchClient.Search[TDocument](Func`2 selector) in /home/runner/work/opensearch-net/opensearch-net/src/OpenSearch.Client/OpenSearchClient.NoNamespace.cs:line 859
2023-11-13T10:32:06.5041694Z    at Tests.Reproduce.GitHubIssue4573.<>c.<SerializePercentageScore>b__0_0() in /home/runner/work/opensearch-net/opensearch-net/tests/Tests.Reproduce/GitHubIssue4573.cs:line 43
2023-11-13T10:32:06.5044045Z    at FluentAssertions.Specialized.FunctionAssertionHelpers.NotThrow[T](Func`1 subject, String because, Object[] becauseArgs).
2023-11-13T10:32:06.5117297Z   Stack Trace:
2023-11-13T10:32:06.5118270Z      at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
2023-11-13T10:32:06.5119634Z    at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
2023-11-13T10:32:06.5121127Z    at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
2023-11-13T10:32:06.5122625Z    at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
2023-11-13T10:32:06.5123985Z    at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
2023-11-13T10:32:06.5125735Z    at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
2023-11-13T10:32:06.5127628Z    at FluentAssertions.Specialized.FunctionAssertionHelpers.NotThrow[T](Func`1 subject, String because, Object[] becauseArgs)
2023-11-13T10:32:06.5129588Z    at FluentAssertions.Specialized.FunctionAssertions`1.NotThrow(String because, Object[] becauseArgs)
2023-11-13T10:32:06.5132274Z    at Tests.Reproduce.GitHubIssue4573.SerializePercentageScore() in /home/runner/work/opensearch-net/opensearch-net/tests/Tests.Reproduce/GitHubIssue4573.cs:line 43
2023-11-13T10:32:07.1686373Z --------
2023-11-13T10:32:07.1687172Z Individual cluster running times:
2023-11-13T10:32:07.1688012Z --------
2023-11-13T10:32:07.1702462Z Failed collections:
2023-11-13T10:32:07.1705949Z  - UNKNOWN: Tests.Reproduce.GitHubIssue4573
2023-11-13T10:32:07.1707541Z ---Reproduce: -----
2023-11-13T10:32:07.1721923Z ./build.sh seed:17695 random:sourceserializer:false random:typedkeys random:httpcompression:false test "githubissue4573"
```

**Comment by Xtansia** [comment]
After investigation 4573 isn't flaky, it's caused by another test: #657
