### ISSUE TITLE
[BUG] System.TypeLoadException thrown on new client initialization 

### ISSUE THREAD

**Issue by EDTCorey** [opensearch-project/opensearch-net#48]
**What is the bug?**
Using OpensearchClient Version 1.0.0.0
After initializing a client a System.TypeLoadException is thrown.
Message:
`System.TypeLoadException: Type 'OpenSearch.Client.OpenSearchClientFormatterResolver' from assembly 'OpenSearch.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d' is attempting to implement an inaccessible interface.` 

Occurring in my main project as well as a basic  .Net 6 console application (Shown below)

**How can one reproduce the bug?**
Initial a new client using the code below and run the program

**What is the expected behavior?**
The client does not crash upon initialization 
 
**Do you have any screenshots?**
Using the below code to test the initialization of the client
![image](https://user-images.githubusercontent.com/102001783/173277233-f8c24c5f-04ee-43cd-a710-c2e06097302e.png)

**Comment by marosbeno** [comment]
I have exactly the same problem. It does not matter what ConnectionString i use, it always results to this exception.

StackTrace:
```
System.TypeLoadException
  HResult=0x80131522
  Message=Type 'OpenSearch.Client.OpenSearchClientFormatterResolver' from assembly 'OpenSearch.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d' is attempting to implement an inaccessible interface.
  Source=OpenSearch.Client
  StackTrace:
   at OpenSearch.Client.ConnectionSettingsBase`1..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializerFactory, IPropertyMappingProvider propertyMappingProvider)
   at OpenSearch.Client.ConnectionSettings..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializer, IPropertyMappingProvider propertyMappingProvider)
   at OpenSearch.Client.ConnectionSettings..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializer)
   at OpenSearch.Client.ConnectionSettings..ctor(IConnectio
```nPool connectionPool)
   at OpenSearch.Client.ConnectionSettings..ctor(Uri uri)

**Comment by GenPike** [comment]
Have the same problem, when tried to set JsonNetSerializer explicitly, so needed to replace "Osc" namespaces to "OpenSearch.Net".
StackTrace:
`System.TypeLoadException: Type 'OpenSearch.Client.OpenSearchClientFormatterResolver' from assembly 'OpenSearch.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d' is attempting to implement an inaccessible interface.
   at OpenSearch.Client.ConnectionSettingsBase`1..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializerFactory, IPropertyMappingProvider propertyMappingProvider)
   at OpenSearch.Client.ConnectionSettings..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializer, IPropertyMappingProvider propertyMappingProvider)
   at OpenSearch.Client.ConnectionSettings..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializer)
   at OpenSearch.Client.ConnectionSettings..ctor(IConnectionPool connectionPool)
   at ElasticCleanup.WalletOpenSearchClient.GetConnectionSettings(Boolean isStage) in C:\Users\oleksii.ishchuk\Desktop\ElasticCleanup\ElasticCleanup\WalletOpenSearchClient.cs:line 80
   at ElasticCleanup.WalletOpenSearchClient..ctor(Boolean isStage) in C:\Users\oleksii.ishchuk\Desktop\ElasticCleanup\ElasticCleanup\WalletOpenSearchClient.cs:line 16
   at Program.<Main>$(String[] args) in C:\Users\oleksii.ishchuk\Desktop\ElasticCleanup\ElasticCleanup\Program.cs:line 40`

**Comment by Yury-Fridlyand** [comment]
@EDTCorey, @GenPike, @marosbeno,
Please recheck if it is still relevant and re-open this ticket if needed.
.Net client was re-released recently.
